import unittest
from test_bin_by_coordinates import TestBinByCoordinates
from test_binned_select_knn import TestBinnedSelectKnn
from test_index_replacer import TestIndexReplacer
from test_oc_helper import TestOcHelper
from test_torch_geometric_interface import TestRowSplitsFromStrictBatch, TestStrictBatchFromRowSplits
from test_gnn_ops import TestGravNetOp
from test_object_condensation import TestObjectCondensation, TestObjectCondensationTraining
from test_oc_helper_helper import TestObjectCondensationHelperHelper


if __name__ == '__main__':
    unittest.main()